---
driver:
  name: vagrant

provisioner:
  name: shell
  script: provision.ps1

platforms:
- name: windows-2016
  driver_config:
    box: stefanscherer/windows_2016

verifier:
  name: pester
  remove_builtin_pester: false
  remove_builtin_powershellget: false

suites:
  - name: default
